# Change these first
owner: ilovetocode2019 # Your GitHub organization or username, where this repository lives
repo: chatom-uptime # The name of this repository

sites:
  - name: Web Client
    url: https://chat.ilovetocode2019.com
  - name: API
    url: https://api.chat.ilovetocode2019.com
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /chatom-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Chatom
  introTitle: Chatom Status
  navbar:
    - title: Status
      href: /chatom-uptime
    - title: Website
      href: https://chat.ilovetocode2019.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
